# -*- coding: utf-8 -*-
C=dict(
slug='ajinomoto',
name='味の素',
legal='味の素株式会社',
ind='食品',
article='ajinomoto-newbusiness',
evsrc={
 '1998.10|味の素ファインテクノ 設立': ['https://www.ajinomoto.co.jp/company/jp/aboutus/history/pdf/2nd-century-2_04.pdf', '味の素グループ 社史'],
 '1999.01|ABF（味の素ビルドアップフィルム）誕生': ['https://www.ajinomoto.co.jp/company/jp/aboutus/history/pdf/2nd-century-2_04.pdf', '味の素グループ 社史'],
 '1999.12|味の素ファルマ 設立': ['https://www.ajinomoto.co.jp/company/jp/aboutus/history/chronology/index.html', '味の素グループ年表'],
 '2003.04|J-オイルミルズ 設立': ['https://www.ajinomoto.co.jp/company/jp/aboutus/history/chronology/index.html', '味の素グループ 年表（社史・沿革）'],
 '2005.04|味の素メディカル 設立': ['https://www.ajinomoto.co.jp/company/jp/aboutus/history/chronology/index.html', '味の素グループ 年表（社史・沿革）'],
 '2011.04|アミノインデックス 事業開始': ['https://www.ajinomoto.co.jp/company/jp/aboutus/history/chronology/index.html', '味の素グループ 年表（社史・沿革）'],
 '2014.02|StemFit 開発成功': ['https://www.ajinomoto.co.jp/company/jp/aboutus/history/chronology/index.html', '味の素グループ年表'],
 '2015.04|味の素ゼネラルフーヅを完全子会社化': ['https://agf.ajinomoto.co.jp/company/history.html', '味の素AGF 沿革'],
 '2015.08|ブラジル即席麺合弁の全持分を譲渡': ['https://www.ajinomoto.co.jp/company/jp/presscenter/press/detail/2015_08_27_2.html', '味の素 プレスリリース'],
 '2015.08|欧州甘味料事業を譲渡': ['https://www.nihon-ma.co.jp/news/20150827_2802-4/', '日本M&Aセンター M&Aニュース'],
 '2016.04|EAファーマ 発足': ['https://www.eapharma.co.jp/company/history', 'EAファーマ 沿革'],
 '2016.11|Promasidorへ33.33%出資': ['https://www.ajinomoto.co.jp/company/jp/aboutus/history/chronology/index.html', '味の素グループ 年表（社史・沿革）'],
 '2016.12|ジーンデザインを買収': ['https://www.ajinomoto.co.jp/company/jp/presscenter/press/detail/2016_12_09.html', '味の素 ニュースリリース'],
 '2017.11|キャンブルックを買収': ['https://www.ajinomoto.co.jp/company/jp/presscenter/press/detail/2017_11_09.html', '味の素 ニュースリリース'],
 '2018.11|香港アモイ・フードを譲渡': ['https://www.ajinomoto.com/cms_wp_ajnmt_global/wp-content/uploads/pdf/g2018_11_19.pdf', '味の素 ニュースリリース'],
 '2020.12|Nualtraを子会社化': ['https://www.ajinomoto.com/cms_wp_ajnmt_global/wp-content/uploads/pdf/Ajinomoto-Co.-Inc.-Makes-a-Supplements-Company-in-Ireland-a-Wholly-Owned-Subsidiary-2.pdf', '味の素 ニュースリリース'],
 '2023.11|Forge Biologicsを買収': ['https://www.ajinomoto.com/cms_wp_ajnmt_global/wp-content/uploads/pdf/2023_11_13E.pdf', '味の素 ニュースリリース'],
 '2025.04|味の素アルテアを譲渡': ['https://www.ajinomoto.com/cms_wp_ajnmt_global/wp-content/uploads/pdf/2025_04_24_03E.pdf', '味の素 ニュースリリース'],
 '2026.03|電子材料が事業利益の3割へ': ['https://www.ajinomoto.co.jp/company/jp/ir/event/presentation/main/011111114/teaserItems1/00/linkList/01/link/FY25Q4_Results_J.pdf', '味の素 2026年3月期 決算概要'],
},
timeline=[
 ('1998.10','味の素ファインテクノ 設立','1998年10月に本社の化成品グループと、三工から改称した味の素ファインテクノを統合して化成品事業を再編。うま味調味料の製造で溜まった樹脂の知見が土台になった',True),
 ('1999.01','ABF（味の素ビルドアップフィルム）誕生','世界初のフィルム状パッケージ基板用絶縁材料。1999年に生まれ、同年に大手半導体メーカー1社へ採用された',True),
 ('1999.12','味の素ファルマ 設立','医薬事業を担う会社として1999年12月に設立。同年10月にはポーランド味の素社も設立している',True),
 ('2003.04','J-オイルミルズ 設立','ホーネンコーポレーション、吉原製油との3社統合で製油事業を切り出した',True),
 ('2005.04','味の素メディカル 設立','医療用食品・輸液の販売会社',True),
 ('2011.04','アミノインデックス 事業開始','血液中のアミノ酸濃度でがんのリスクを測る検査。アミノ酸研究の医療への出口',True),
 ('2014.02','StemFit 開発成功','京都大学iPS細胞研究所と共同で、iPS/ES細胞用の培地「StemFit」AK03の開発に2014年2月に成功した',True),
 ('2015.08','欧州甘味料事業を譲渡','フランスの欧州味の素甘味料社をオランダのHyett Holdingへ',False),
 ('2015.08','ブラジル即席麺合弁の全持分を譲渡','ブラジルの即席麺合弁NISSIN-AJINOMOTO ALIMENTOS の保有持分50%すべてを325億円で日清食品HDへ譲り、特別利益250億円程度を見込むと発表。ブラジルでは調味料などへ経営資源を集中する',False),
 ('2015.04','味の素ゼネラルフーヅを完全子会社化','2015年2月にモンデリーズ社の保有する全株式を270億円で取得することで合意し、同年4月に味の素グループ100%出資の会社となった。社名の味の素AGFへの変更は同年10月',True),
 ('2016.04','EAファーマ 発足','エーザイの消化器領域と統合。医薬を単独で持たない形へ',True),
 ('2016.11','Promasidorへ33.33%出資','約558億円。アフリカの加工食品市場へ',True),
 ('2016.12','ジーンデザインを買収','核酸医薬の受託製造。95%を取得し、CDMOの足場を作った',True),
 ('2017.11','キャンブルックを買収','約72億円。米国のメディカルフード。食と医療の境目へ',True),
 ('2018.11','香港アモイ・フードを譲渡','2006年にダノンから取得した会社を、CITIC系ファンドへ',False),
 ('2020.12','Nualtraを子会社化','アイルランドの栄養食品会社',True),
 ('2023.11','Forge Biologicsを買収','約828億円。米国の遺伝子治療CDMO。過去最大級の投資',True),
 ('2025.04','味の素アルテアを譲渡','医薬品の無菌充填受託会社を米PCIへ。事業の選別を進めた',False),
 ('2026.03','電子材料が事業利益の3割へ','売上1,007億円・事業利益546億円・利益率54.2%',True),
],
sources=[
 ('味の素 2026年3月期 決算概要（セグメント別実績）','https://www.ajinomoto.co.jp/company/jp/ir/event/presentation/main/011111114/teaserItems1/00/linkList/01/link/FY25Q4_Results_J.pdf'),
 ('味の素グループ ABF イノベーションストーリー','https://www.ajinomoto.co.jp/company/jp/rd/our_innovation/abf/'),
 ('味の素グループ 年表（社史・沿革）','https://www.ajinomoto.co.jp/company/jp/aboutus/history/chronology/index.html'),
 ('味の素グループ ヘルスケア事業の展開','https://www.ajinomoto.co.jp/company/jp/ir/business/healthcare_and_others.html'),
 ('味の素のM&Aニュース一覧（日本M&Aセンター）','https://www.nihon-ma.co.jp/news/company/2802/'),
 ('味の素、米Forge Biologicsを約828億円で買収','https://www.nihon-ma.co.jp/news/20231113_2802-15/'),
],
)
