# -*- coding: utf-8 -*-
C=dict(
slug='kddi',
name='KDDI',
legal='KDDI株式会社',
ind='通信',
article='kddi-newbusiness',
evsrc={"2026.08": ['https://newsroom.kddi.com/news/detail/kddi_nr-1112_4640.html', 'KDDI ニュースリリース']},
timeline=[
 ('2026.08','堺市の自動運転タクシー実装へ参画','堺市自動運転タクシー実装コンソーシアムに参画。通信インフラを提供し社会実装を担う',True),
 ('2008.07','auじぶん銀行 開業','三菱東京UFJ銀行との共同出資。通信会社が銀行を持った最初期の例',True),
 ('2010.12','au損害保険 開業','あいおいニッセイ同和損保との共同出資。自転車保険で知られる',True),
 ('2011.08','KDDI ∞ Labo 開始','スタートアップ支援プログラム。出資と事業共創の入口をつくった',True),
 ('2014.10','Syn.構想 発表','他社サービスを横につなぐ連合構想。約120億円を出資し提携網を築いたが、2018年に構想としての役目を終えた',False),
 ('2015.04','au WALLET Market 開始','通信の顧客基盤に物販を乗せる試み。2021年に役目を終えた',False),
 ('2016.04','auでんき 開始','電力小売の全面自由化と同時に参入。通信とのセット割で伸ばした',True),
 ('2017.05','au HOME 開始','家庭内のIoT。センサーとカメラを通信契約に紐づけた',True),
 ('2019.04','au PAY 開始','コード決済。楽天ペイとの加盟店相互開放という珍しい形をとった',True),
 ('2019.12','auカブコム証券 誕生','三菱UFJ側と組み、カブドットコム証券を社名変更。証券を手に入れた',True),
 ('2020.06','GeForce NOW Powered by au 開始','NVIDIAと組んだクラウドゲーム。5年間の提供を走り切った',False),
 ('2021.03','povo 開始','オンライン専用の料金プラン。トッピング型という独自の形をとった',True),
 ('2021.09','au Style 開店','売る場所から、相談する場所へ。店舗の役割を組み替えた',True),
 ('2022.09','KDDIスマートドローン 設立','ドローンの運航管理。通信網を空へ広げる新会社',True),
 ('2023.03','αU 開始','メタバース、ウォレット、ライブ配信を束ねたWeb3サービス群',True),
 ('2023.09','auマネ活プラン 開始','通信と金融を1つの料金プランに束ねた。金融15年の集大成',True),
 ('2024.09','ローソン共同経営 開始','三菱商事と50%ずつ。約4,971億円を投じてリアル店舗を手に入れた',True),
 ('2025.04','au Starlink Direct 開始','SpaceXと組み、圏外でもスマホが衛星と直接つながる',True),
 ('2026.01','大阪堺データセンター 稼働','AI向けの大規模データセンター。通信の次の柱として建てた',True),
],
sources=[
 ('KDDI ニュースリリース一覧','https://newsroom.kddi.com/news/'),
 ('auじぶん銀行 会社沿革','https://www.jibunbank.co.jp/corporate/company/history/'),
 ('au損害保険 会社概要','https://www.au-sonpo.co.jp/corporate/'),
 ('KDDI ∞ Labo 公式サイト','https://www.kddi.com/corporate/kddi/inobe/'),
 ('KDDI「Syn.構想」発表（2014年10月）','https://newsroom.kddi.com/news/detail/kddi_index_1240.html'),
 ('auカブコム証券 会社情報','https://kabu.com/company/'),
 ('povo 公式サイト','https://povo.jp/'),
 ('KDDIスマートドローン 会社概要','https://kddi.smartdrone.co.jp/company/'),
 ('KDDI・三菱商事 ローソンとの資本業務提携（2024年2月）','https://newsroom.kddi.com/news/detail/kddi_pr_secret-79.html'),
 ('三菱商事 ローソンとの新たな資本業務提携について','https://www.mitsubishicorp.com/jp/ja/news/release/2024/0000052862.html'),
 ('au Starlink Direct 公式サイト','https://www.au.com/mobile/area/starlink-direct/'),
],
)
