# -*- coding: utf-8 -*-
C=dict(
slug='lycorp',
name='LINEヤフー',
legal='LINEヤフー株式会社',
ind='IT',
article=None,
evsrc={
 '1996.01|ヤフー株式会社 設立': ['https://www.lycorp.co.jp/ja/company/history/yahoo/', 'LINEヤフー 沿革（ヤフー株式会社）'],
 '1999.09|ヤフオク・Yahoo!ショッピング開始': ['https://www.lycorp.co.jp/ja/company/history/yahoo/', 'LINEヤフー 沿革（ヤフー株式会社）'],
 '2001.09|Yahoo! BB 開始': ['https://www.lycorp.co.jp/ja/company/history/yahoo/', 'LINEヤフー 沿革（ヤフー株式会社）'],
 '2002.11|検索連動型広告 開始': ['https://www.lycorp.co.jp/ja/company/history/yahoo/', 'LINEヤフー 沿革（ヤフー株式会社）'],
 '2004.04|Yahoo!知恵袋 開始': ['https://www.lycorp.co.jp/ja/company/history/yahoo/', 'LINEヤフー 沿革（ヤフー株式会社）'],
 '2011.06|LINE 提供開始': ['https://www.lycorp.co.jp/ja/company/history/line/', 'LINEヤフー 沿革（LINE株式会社）'],
 '2012.04|アスクルと業務・資本提携': ['https://www.lycorp.co.jp/ja/company/history/yahoo/', 'LINEヤフー 沿革（ヤフー株式会社）'],
 '2012.11|LINE GAME 開始': ['https://www.lycorp.co.jp/ja/company/history/line/', 'LINEヤフー 沿革（LINE株式会社）'],
 '2013.03|LINE Plus Corporation 設立': ['https://www.lycorp.co.jp/ja/company/history/line/', 'LINEヤフー 沿革（LINE株式会社）'],
 '2013.07|LINE NEWS 開始': ['https://www.lycorp.co.jp/ja/company/history/line/', 'LINEヤフー 沿革（LINE株式会社）'],
 '2015.01|ワイジェイカードの株式取得': ['https://www.lycorp.co.jp/ja/company/history/yahoo/', 'LINEヤフー 沿革（ヤフー株式会社）'],
 '2015.04|LINEギフト 開始': ['https://www.lycorp.co.jp/ja/company/history/line/', 'LINEヤフー 沿革（LINE株式会社）'],
 '2016.02|一休の株式取得': ['https://www.lycorp.co.jp/ja/company/history/yahoo/', 'LINEヤフー 沿革（ヤフー株式会社）'],
 '2016.06|LINE広告 開始': ['https://www.lycorp.co.jp/ja/company/history/line/', 'LINEヤフー 沿革（LINE株式会社）／2016年6月「LINE Ads Platform」開始'],
 '2016.07|LINE 米国・東京市場へ上場': ['https://www.lycorp.co.jp/ja/company/history/line/', 'LINEヤフー 沿革（LINE株式会社）'],
 '2018.02|ジャパンネット銀行の株式取得': ['https://www.lycorp.co.jp/ja/company/history/yahoo/', 'LINEヤフー 沿革（ヤフー株式会社）'],
 '2018.06|PayPay株式会社 設立': ['https://www.lycorp.co.jp/ja/company/history/yahoo/', 'LINEヤフー 沿革（ヤフー株式会社）'],
 '2018.10|PayPay サービス開始': ['https://www.lycorp.co.jp/ja/company/history/yahoo/', 'LINEヤフー 沿革（ヤフー株式会社）'],
 '2019.10|PayPayフリマ 開始': ['https://www.lycorp.co.jp/ja/company/history/yahoo/', 'LINEヤフー 沿革（ヤフー株式会社）'],
 '2019.10|持株会社化とZホールディングス発足': ['https://www.lycorp.co.jp/news/archive/Z/ja/ja20190425.pdf', '会社分割による持株会社体制への移行に伴う分割準備会社設立、吸収分割契約締結及び定款変更（商号変更）に関するお知らせ'],
 '2019.11|ZOZOの株式取得': ['https://www.lycorp.co.jp/news/archive/Z/ja/ja20191114.pdf', '株式会社ZOZO株式（証券コード 3092）に対する公開買付けの結果及び子会社の異動に関するお知らせ'],
 '2019.12|Yahoo!ブログ 提供終了': ['https://www.lycorp.co.jp/news/archive/Y/ja/ja20191129_B.pdf', '2020年3月末日までに提供を終了するアプリ／サービスについて'],
 '2020.03|出前館への資本業務提携': ['https://www.lycorp.co.jp/ja/company/history/line/', 'LINEヤフー 沿革（LINE株式会社）'],
 '2020.10|LINE BK 開始（タイ）': ['https://www.lycorp.co.jp/ja/company/history/line/', 'LINEヤフー 沿革（LINE株式会社）'],
 '2021.03|ZホールディングスとLINEの統合': ['https://www.lycorp.co.jp/news/archive/Z/ja/ja20210301_B.pdf', 'ZホールディングスとLINEの経営統合が完了'],
 '2021.04|Z Venture Capital 事業開始': ['https://www.lycorp.co.jp/news/archive/Z/ja/ja20210401.pdf', 'ＹＪキャピタルとLINE Venturesが合併、Z Venture Capitalとして本日より事業開始'],
 '2021.11|LINE VOOM 開始': ['https://www.lycorp.co.jp/ja/company/history/line/', 'LINEヤフー 沿革（LINE株式会社）'],
 '2023.06|LINE証券の証券事業を野村へ移管': ['https://www.lycorp.co.jp/news/archive/L/ja/ja20230612_A.pdf', 'LINE証券の事業再編に関するお知らせ'],
 '2023.10|LINEヤフー株式会社 発足': ['https://www.lycorp.co.jp/ja/news/release/000846/', '「LINEヤフー株式会社」発足'],
 '2023.11|LYPプレミアム 開始': ['https://www.lycorp.co.jp/ja/company/history/lycorp/', 'LINEヤフー 沿革（LINEヤフー株式会社）'],
 '2024.06|LINE Pay 国内サービスの終了を発表': ['https://www.lycorp.co.jp/ja/news/release/008628/', '日本国内における「LINE Pay」サービス終了に関するお知らせ'],
 '2024.07|SeekAI 全社導入': ['https://www.lycorp.co.jp/ja/news/release/008806/', 'RAG技術を活用した独自業務効率化ツール「SeekAI」を全従業員に本格導入'],
 '2024.12|LINE Pay Taiwan 台湾市場へ上場': ['https://www.lycorp.co.jp/ja/company/history/lycorp/', 'LINEヤフー 沿革（LINEヤフー株式会社）'],
 '2025.01|ZVC2号投資事業組合 組成': ['https://www.lycorp.co.jp/ja/news/release/016769/', 'Z Venture Capital株式会社、300億円規模の新ファンド「ZVC2号投資事業組合」を組成'],
 '2025.02|PayPay証券の株式をPayPayへ譲渡': ['https://about.paypay.ne.jp/pr/20250210/01/', 'PayPayによるPayPay証券の株式取得および第三者割当増資引受について（PayPay）'],
 '2025.04|Yahoo! JAPANとLINEに生成AI': ['https://www.lycorp.co.jp/ja/company/history/lycorp/', 'LINEヤフー 沿革（LINEヤフー株式会社）'],
 '2026.01|トレタの株式取得': ['https://www.lycorp.co.jp/ja/news/release/020056/', '飲食店向け予約管理サービスを提供する株式会社トレタの株式取得に関するお知らせ'],
 '2026.03|PayPayが米国ナスダックへ上場': ['https://about.paypay.ne.jp/pr/20260312/01/', '米国預託株式の米国内での新規公開における公開価格発表に関するお知らせ（PayPay）'],
 '2026.07|LINEとPayPayのアカウント連携': ['https://www.lycorp.co.jp/ja/news/release/020581/', '国内月間利用者数1億ユーザーの「LINE」と登録ユーザー7,400万人を抱える「PayPay」のアカウント連携を2026年夏より開始'],
},
timeline=[
 ('1996.01','ヤフー株式会社 設立','ソフトバンクと米ヤフーの2社による合弁として設立。同年4月に日本語ポータルYahoo! JAPANを開始した',True),
 ('1999.09','ヤフオク・Yahoo!ショッピング開始','2サービスを同月に開始。広告に次ぐ収益柱となるコマース領域へ本格参入した',True),
 ('2001.09','Yahoo! BB 開始','ソフトバンクグループのADSL接続サービスとして開始。広告以外の通信・会員課金領域へ事業を広げる転機となった',True),
 ('2002.11','検索連動型広告 開始','検索キーワードに連動する広告商品を開始。主力事業へ成長し、翌2003年10月には東証一部への上場を果たした',True),
 ('2004.04','Yahoo!知恵袋 開始','利用者同士が質問と回答を投稿するQ&Aサービスを開始。検索流入を支える投稿型コンテンツ基盤を自社で確保した',True),
 ('2011.06','LINE 提供開始','NHN Japanがメッセージアプリを開始。2025年12月に国内月間利用者数1億を突破した',True),
 ('2012.04','アスクルと業務・資本提携','同年10月に個人向け通販LOHACOを共同で開始し、日用品EC領域へ2社体制で参入した',True),
 ('2012.11','LINE GAME 開始','LINE上のゲームプラットフォームを開始。同年5月のLINE公式アカウント、12月のLINE@と合わせ3つの収益事業を同年に立ち上げた',True),
 ('2013.03','LINE Plus Corporation 設立','海外展開の拠点として韓国に設立。2014年9月に完全子会社化し、タイ・台湾など複数国の事業基盤とした',True),
 ('2013.07','LINE NEWS 開始','LINE上のニュース配信サービスを開始。同年4月のLINE占いと合わせ、2つのコンテンツ事業を立ち上げた',True),
 ('2015.01','ワイジェイカードの株式取得','現PayPayカードの株式を取得しクレジットカード事業へ参入。金融領域で1社目の主要子会社となった',True),
 ('2015.04','LINEギフト 開始','LINE上で贈り物を送れるサービスを開始。同年6月にはLINE MUSICも開始し、2つの新規サービスを相次いで立ち上げた',True),
 ('2016.02','一休の株式取得','宿泊・レストラン予約の一休を公開買付けで買収し子会社化。買収規模は約1,000億円で、当時のヤフーとして最大級の案件',True),
 ('2016.06','LINE広告 開始','LINE上の広告配信サービスを開始。同月のLINE TODAY、11月のLINEリサーチと合わせ、広告・調査の3事業を同年に整えた',True),
 ('2016.07','LINE 米国・東京市場へ上場','ニューヨーク証券取引所と東京証券取引所の2市場へ同時上場。経営統合に伴い2020年12月に両市場での上場を終えた',False),
 ('2018.02','ジャパンネット銀行の株式取得','現PayPay銀行の株式を取得し銀行事業への関与を強化。2021年4月にPayPay銀行へ商号を変更した',True),
 ('2018.06','PayPay株式会社 設立','ソフトバンクとの共同出資でPay株式会社を設立し、同年7月にPayPay株式会社へ商号変更。インドPaytmの技術を活用する体制とした',True),
 ('2018.10','PayPay サービス開始','QRコード決済を開始。口座数4,000万超のYahoo!ウォレット基盤を活用し、ユーザー読み取り方式は加盟店手数料を3年間無料とした',True),
 ('2019.10','持株会社化とZホールディングス発足','ヤフーが持ち株会社体制へ移行し商号変更。2023年10月のLINEヤフー発足に伴い、この商号での運営を終えた',False),
 ('2019.10','PayPayフリマ 開始','フリマアプリを開始。同月にビッグデータ活用のヤフー・データソリューションも開始し、2つの新規事業を同時に立ち上げた',True),
 ('2019.11','ZOZOの株式取得','公開買付けでZOZOの議決権50.1%を約4,007億円で取得し連結子会社化。ファッションEC最大手を取り込んだ',True),
 ('2019.12','Yahoo!ブログ 提供終了','ブログサービスは2019年2月に終了を発表し、同年12月15日に提供を終えた。利用者には他サービスへの移行を案内した',False),
 ('2020.03','出前館への資本業務提携','LINEとNAVER系ファンドが計約300億円を出資。LINEの議決権比率は35.87%となり、フードデリバリー領域へ本格参入した',True),
 ('2020.10','LINE BK 開始（タイ）','タイでLINE上のバンキングサービスを開始。2021年4月に台湾、6月にインドネシアと、3つの国・地域で銀行サービスを立ち上げた',True),
 ('2021.03','ZホールディングスとLINEの統合','3月1日に経営統合が完了。従業員2.3万人、延べ利用者3億超の規模となり、2023年度に売上高2兆円を目標として掲げた',True),
 ('2021.04','Z Venture Capital 事業開始','YJキャピタルとLINE Venturesが合併し始動。300億円規模の新ファンドを組成しスタートアップ投資を進めた',True),
 ('2021.11','LINE VOOM 開始','LINE上の動画プラットフォームを開始。同年3月のLINEスキマニと合わせ、2つの新規サービスを同年に立ち上げた',True),
 ('2023.06','LINE証券の証券事業を野村へ移管','いちかぶなど証券サービスの提供を終え、150万口座超の資産を野村證券へ移管すると発表。2024年に事業再編を完了した',False),
 ('2023.10','LINEヤフー株式会社 発足','Zホールディングス、LINE、ヤフーなど5社のグループ内再編が完了し発足。Yahoo! JAPAN 5,430万、LINE 1億9,900万の利用者基盤を統合した',True),
 ('2023.11','LYPプレミアム 開始','Yahoo!プレミアムをリブランドし、LINE関連特典を統合した会員サービスへ移行。11月29日から新名称での提供を始めた',True),
 ('2024.06','LINE Pay 国内サービスの終了を発表','国内登録者4,400万人超のLINE Payは2025年4月30日に提供を終え、送金・決済をPayPayへ一本化した',False),
 ('2024.07','SeekAI 全社導入','社内文書を横断検索するRAG活用ツールを全従業員へ本格導入。年間70〜80万時間の業務削減を目標に掲げた',True),
 ('2024.12','LINE Pay Taiwan 台湾市場へ上場','子会社のLINE Pay Taiwan Limitedが台湾証券取引所へ上場。台湾の決済事業を1社の上場企業として運営する体制とした',True),
 ('2025.01','ZVC2号投資事業組合 組成','Z Venture CapitalがAI・ディープテックなどを対象に300億円規模の新ファンドを組成した',True),
 ('2025.02','PayPay証券の株式をPayPayへ譲渡','2月10日発表。ソフトバンクとLINEヤフーが持つPayPay証券株式をPayPayが取得し子会社化する金融事業の集約再編',False),
 ('2025.04','Yahoo! JAPANとLINEに生成AI','Yahoo! JAPANアプリでAIアシスタント機能、LINEでLINE AIとLINE AIトークサジェストの2機能を始動した',True),
 ('2026.01','トレタの株式取得','飲食店向け予約管理サービスのトレタの株式を取得し子会社化へ。累計19,000店舗超の導入実績を持つ予約基盤を取り込む',True),
 ('2026.03','PayPayが米国ナスダックへ上場','連結子会社のPayPayが米国預託株式をナスダックへ新規公開。3月12日にティッカーPAYPで取引を開始した',True),
 ('2026.07','LINEとPayPayのアカウント連携','国内月間利用者1億のLINEと登録ユーザー7,400万人のPayPayのアカウント連携を、2026年夏から開始すると発表した',True),
],
sources=[
 ('LINEヤフー 沿革（ヤフー株式会社）','https://www.lycorp.co.jp/ja/company/history/yahoo/'),
 ('LINEヤフー 沿革（LINE株式会社）','https://www.lycorp.co.jp/ja/company/history/line/'),
 ('LINEヤフー 沿革（LINEヤフー株式会社）','https://www.lycorp.co.jp/ja/company/history/lycorp/'),
 ('LINEヤフー株式会社 発足','https://www.lycorp.co.jp/ja/news/release/000846/'),
 ('日本国内におけるLINE Payサービス終了に関するお知らせ','https://www.lycorp.co.jp/ja/news/release/008628/'),
 ('SeekAIを全従業員に本格導入','https://www.lycorp.co.jp/ja/news/release/008806/'),
 ('Z Venture Capital ZVC2号投資事業組合を組成','https://www.lycorp.co.jp/ja/news/release/016769/'),
 ('株式会社トレタの株式取得に関するお知らせ','https://www.lycorp.co.jp/ja/news/release/020056/'),
 ('LINEとPayPayのアカウント連携を2026年夏より開始','https://www.lycorp.co.jp/ja/news/release/020581/'),
],
)
