# -*- coding: utf-8 -*-
C=dict(
slug='recruit',
name='リクルート',
legal='株式会社リクルートホールディングス',
ind='人材',
article='recruit-newbusiness',
timeline=[
 ('2015.01','Peoplebank Holdings（豪）を子会社化','豪州のIT人材派遣会社',True),
 ('2015.03','Quandoo（独）を子会社化','欧州の飲食店予約サービス',True),
 ('2015.04','Chandler Macleod Group（豪）を子会社化','豪州の総合人材サービス会社',True),
 ('2015.05','Hotspring Ventures（英）を取得','欧州の美容予約サービス。2020年6月に別会社へ移した',False),
 ('2015','Recruit Institute of Technology 設立','シリコンバレーのAI研究所。のちにMegagon Labsへ改称',True),
 ('2015.11','Airペイ リリース','iPad決済端末。Airレジから広がる「Air ビジネスツールズ」の中核',True),
 ('2016.04','スタディサプリへ統合','受験サプリを終了し、月額制の動画学習サービスに一本化',True),
 ('2016.06','USG People（蘭）を子会社化','欧州の人材派遣大手。のちにRGF Staffingへ',True),
 ('2018.04','Airシフト リリース','シフト作成・管理ツール。Airシリーズを労務側へ拡張',True),
 ('2018.05','Glassdoor 買収を発表','企業口コミ・給与情報サイト。12億米ドル、約1,272億円。2025年7月にIndeedへ統合した',False),
 ('2021.01','Airカード／Airワーク採用管理','Airシリーズを金融とHRへ拡張',True),
 ('2022.04','Airキャッシュ／Airインボイス','事業者向けの資金調達と請求業務のデジタル化',True),
 ('2023.04','Airワーク 給与支払 リリース','給与計算・支払いまでAirシリーズに取り込んだ',True),
 ('2024','Indeed PLUS（日本）リリース','国内求人メディアの原稿をIndeedに集約する仕組み',True),
 ('2025.04','セグメント再編','人材領域をHRテクノロジーへ移管。旧区分はMMTへ改称',True),
 ('2025.07','GlassdoorをIndeedへ統合','HRテクノロジー部門で約1,300人の体制見直しをあわせて発表',False),
],
sources=[
 ('リクルートホールディングス 沿革','https://recruit-holdings.com/ja/about/history/'),
 ('リクルートHD：Glassdoorの買収について（2018年5月9日）','https://recruit-holdings.com/ja/newsroom/20180509_8170/'),
 ('Air ビジネスツールズ 歩み','https://airregi.jp/brand/history/'),
 ('リクルートHD：2026年3月期 決算短信','https://recruit-holdings.com/ja/ir/library/upload/recruit_202603q4_earnings_jp/'),
 ('リクルートHD：2025年3月期 決算短信','https://recruit-holdings.com/ja/ir/library/upload/recruit_202503q4_earnings_jp/'),
 ('Bloomberg：Indeed・Glassdoorの統合について（2025年7月）','https://www.bloomberg.com/jp/news/articles/2025-07-10/SZ75XRDWX2PS00'),
 ('リクルートホールディングス IRライブラリ','https://recruit-holdings.com/ja/ir/library/'),
],
)
